# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WhistScoreHolder' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'SideMenu'
  
  use_frameworks!

  # Pods for WhistScoreHolder

  target 'WhistScoreHolderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
